modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"

logoFile="logo.png"

authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="irons_spellbooks"
    mandatory=true
    # 使用 [0,) 来接受任何版本，因为 Iron's Spells 的版本格式是 1.20.1-3.15.6
    # 这种格式会导致版本解析问题
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
